name: google_charts
version: 0.1.3+2
author: Robert Hartung <robert.w.hartung@gmail.com>
description: Google Charts API Wrapper Classes.
homepage: https://github.com/roberthartung/google_charts
dev_dependencies:
  html: any
  http: any
