name: google_charts
version: 0.1.3+2
author: Robert Hartung <robert.w.hartung@gmail.com>
description: Google Charts API Wrapper Classes.
homepage: https://github.com/roberthartung/google_charts
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
dev_dependencies:
  html: any
  http: any
